version: "3.7"
networks:
  network-transactions:
    driver: bridge

services:
  transactions_database:
    image: mysql/mysql-server:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - network-transactions
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - network-transactions
    ports:
      - 5672:5672
      - 15672:15672
  transactions_app:
    image: transactions_app/app
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - network-transactions
    depends_on:
      transactions_database:
        condition: service_healthy
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
